version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes: 
      - .:/app
    depends_on: 
      - mongo
    ports:
      - "3000:3000"
  
  mongo:
    container_name: mongo
    image: mongo:8
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: cronoclick
    volumes:
      - ./data:/data/db