version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
      - ./docker:/docker
    ports:
      - "3000:3000"
    command: >
      bash -c "
        bash /docker/entry-prisma.sh &&
        npm run dev
      "